name: Feature request
description: Request a new feature or improvement
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes: { label: Summary, description: What and why }
    validations: { required: true }
  - type: textarea
    id: ux
    attributes: { label: UX sketch, description: Menu location, settings, workflow }
  - type: textarea
    id: scope
    attributes: { label: Scope, description: MVP vs nice-to-have }
